language: scala


services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.9.0-rc4
  CODACY_PROJECT_TOKEN: %1708aff745054f258eb4917cf2191051%


before_install:
  - docker build -t keyskull/postssystem .
  - docker run -d -P 41658:41658  keyskull/postssystem -s


script:
  - sbt clean coverage test coverageReport &&
    sbt coverageAggregate
  - sbt ++$TRAVIS_SCALA_VERSION test

